[program:autocron-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/autocron
command=/usr/bin/php artisan queue:work --queue=cron-high,cron-default,cron-low,mails,user-logs --sleep=1 --tries=1 --timeout=180 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/autocron-worker.log
stopwaitsecs=200

