[program:autocron-scheduler]
process_name=%(program_name)s
directory=/var/www/autocron
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/autocron-scheduler.log
stopwaitsecs=60

