[program:dailyproxy-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/dailyproxy.vn/laravel-app
command=/usr/bin/php artisan queue:work --queue=default,mails,user-logs --sleep=3 --tries=3 --timeout=120 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dailyproxy-worker.log
stopwaitsecs=180
