[program:dailyproxy-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/dailyproxy.vn/laravel-app
command=/usr/bin/php artisan queue:work --queue=default,mails,user-logs --sleep=3 --tries=3 --timeout=60 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dailyproxy-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=3600

[program:dailyproxy-scheduler]
process_name=%(program_name)s
directory=/var/www/dailyproxy.vn/laravel-app
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dailyproxy-scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=60

[program:dailyproxy-reverb]
process_name=%(program_name)s
directory=/var/www/dailyproxy.vn/laravel-app
command=/usr/bin/php artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dailyproxy-reverb.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=60

[group:dailyproxy]
programs=dailyproxy-worker,dailyproxy-scheduler,dailyproxy-reverb
priority=999
