[program:xemphatnguoi-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/home/xemphatnguoivn/xemphatnguoi.vn
command=/usr/bin/php8.2 /home/xemphatnguoivn/xemphatnguoi.vn/artisan queue:work --queue=default,mails,user-logs --sleep=1 --tries=3 --timeout=60 --backoff=3 --memory=256 --max-time=3600 --no-interaction
autostart=true
autorestart=true
startsecs=10
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=120
user=xemphatnguoivn
numprocs=2
redirect_stderr=true
stdout_logfile=/home/xemphatnguoivn/xemphatnguoi.vn/storage/logs/queue-worker-%(process_num)02d.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=HOME="/home/xemphatnguoivn",USER="xemphatnguoivn"

[program:xemphatnguoi-scheduler]
process_name=%(program_name)s
directory=/home/xemphatnguoivn/xemphatnguoi.vn
command=/usr/bin/php8.2 /home/xemphatnguoivn/xemphatnguoi.vn/artisan schedule:work --no-interaction
autostart=true
autorestart=true
startsecs=10
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=60
user=xemphatnguoivn
numprocs=1
redirect_stderr=true
stdout_logfile=/home/xemphatnguoivn/xemphatnguoi.vn/storage/logs/scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=HOME="/home/xemphatnguoivn",USER="xemphatnguoivn"

[program:xemphatnguoi-reverb]
process_name=%(program_name)s
directory=/home/xemphatnguoivn/xemphatnguoi.vn
command=/usr/bin/php8.2 /home/xemphatnguoivn/xemphatnguoi.vn/artisan reverb:start --host=127.0.0.1 --port=8080 --no-interaction
autostart=true
autorestart=true
startsecs=5
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=30
user=xemphatnguoivn
numprocs=1
redirect_stderr=true
stdout_logfile=/home/xemphatnguoivn/xemphatnguoi.vn/storage/logs/reverb.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=HOME="/home/xemphatnguoivn",USER="xemphatnguoivn"

[group:xemphatnguoi]
programs=xemphatnguoi-worker,xemphatnguoi-scheduler,xemphatnguoi-reverb
priority=999
