<?php

return [
    'minimum_amount' => 50_000,
    'maximum_amount' => 100_000_000,
    'bonus_percentage' => 10,
    'default_per_page' => 10,
    'methods' => [
        'banking' => [
            'active' => true,
            'label' => 'Chuyển khoản ngân hàng',
            'description' => 'Đối soát tự động.',
            'badge_label' => 'Tự động',
            'badge_type' => 'auto',
            'bank_name' => 'Vietcombank',
            'account_number' => '1029384756',
            'account_name' => 'CONG TY TNHH CLIENT PANEL',
        ],
        'momo' => [
            'active' => false,
            'label' => 'Ví MoMo',
            'description' => 'Xác nhận nhanh.',
            'badge_label' => 'Tự động',
            'badge_type' => 'auto',
            'bank_name' => 'MoMo Business',
            'account_number' => '0909123456',
            'account_name' => 'CLIENT PANEL WALLET',
        ],
        'vnpay' => [
            'active' => false,
            'label' => 'VNPay QR',
            'description' => 'Quét mã để thanh toán.',
            'badge_label' => 'Tự động',
            'badge_type' => 'auto',
            'bank_name' => 'VNPay Gateway',
            'account_number' => 'VNP-102938',
            'account_name' => 'CLIENT PANEL QR',
        ],
        'card' => [
            'active' => false,
            'label' => 'Thẻ ATM / Visa / Master',
            'description' => 'Qua cổng thẻ.',
            'badge_label' => 'Thủ công',
            'badge_type' => 'manual',
            'bank_name' => 'Payment Gateway',
            'account_number' => 'CARD-889900',
            'account_name' => 'CLIENT PANEL CARD',
        ],
    ],
];
